[tool.poetry]
name = "cookiecutter-action-py"
version = "0.1.0"
description = "A cookiecutter template for generating Github actions running Python"
authors = ["Bruno Alla <alla.brunoo@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
cookiecutter = "^1.7.2"
binaryornot = "^0.4.4"
black = "^20.8b1"
flake8 = "^3.8.4"
isort = "^5.6.4"
pytest = "^6"
pytest-cookies = "^0.6.0"
pyupgrade = {version = "^2.7.4", python = "^3.6.1"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
known_first_party = ["src"]
