# Run pre-commit autoupdate every day at midnight
# and create a pull request if any changes

name: Pre-commit auto-update

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.8
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.4.0
        with:
          # CI won't be running on pull requests if using GITHUB_TOKEN
          # We instead use a personal access token (PAT) with the 'repo' scope
          # https://github.com/settings/tokens/new?scopes=repo
          token: {% raw %}${{ secrets.GH_PAT }}{% endraw %}
          branch: update/pre-commit-autoupdate
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of tools in pre-commit configs to latest version.
          labels: dependencies
