name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        script:
          - flake8 --config=setup.cfg
          - black --check .
          - pyupgrade --py3-plus `find . -name "*.py"`
          - isort -c -v .
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Python
      uses: actions/setup-python@v2.1.2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - run: {% raw %}${{ matrix.script }}{% endraw %}

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2.1.0
