name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: "true"
      - run: uv sync --no-python-downloads
      - name: Test with Pytest
        run: poetry run pytest
