name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Python
      uses: actions/setup-python@v2.1.2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: Test with Pytest
      run: pytest

  lint:
    strategy:
      matrix:
        linter:
          - name: Flake8
            run: flake8 --config=setup.cfg tests.py
          - name: Black
            run: black --check tests.py
          - name: PyUpgrade
            run: pyupgrade --py36-plus tests.py
          - name: isort
            run: isort -c -v tests.py
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Python
      uses: actions/setup-python@v2.1.2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: ${{ matrix.linter.name }}
      run: ${{ matrix.linter.run }}
